version: "3.3"
services:

  backend:
    build:
      context: ./app
      network: host
    command: ["/app/tools/run.sh"]
    volumes:
      - static_volume:/app/staticfiles
    environment:
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "password"
      ADMIN_EMAIL: "admin@example.com"
      DATABASE_URL: "postgres://doccano:doccano@postgres:5432/doccano?sslmode=disable"
      ALLOW_SIGNUP: "False"
      DEBUG: "False"
    depends_on:
      - postgres
    networks:
      - network-backend
      - network-frontend
    image: asc686f61/doccano_backend:v1.0

  frontend:
    build:
      context: ./frontend
      network: host
    volumes:
      - www:/app/dist
    environment:
      GOOGLE_TRACKING_ID: ""
    image: asc686f61/doccano_frontend:v1.0

  nginx:
    build:
      context: ./nginx
      network: host
    volumes:
      - www:/var/www/html:ro
      - static_volume:/static
    ports:
      - 8000:80
    depends_on:
      - backend
    networks:
      - network-frontend
    image: asc686f61/doccano_nginx:v1.0

  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "doccano"
      POSTGRES_PASSWORD: "doccano"
      POSTGRES_DB: "doccano"
    networks:
      - network-backend

volumes:
  postgres_data:
  static_volume:
  www:

networks:
  network-backend:
  network-frontend:
